"""empty message

Revision ID: 005040845e36
Revises: 
Create Date: 2017-11-01 16:27:13.282608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005040845e36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('post_id', sa.String(length=45), nullable=True))
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'post_id')
    # ### end Alembic commands ###
